// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektUrlopWeb.Data;

#nullable disable

namespace ProjektUrlopWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240805081407_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjektUrlopWeb.Models.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("PracownikId_num")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId_num");

                    b.ToTable("Logi");
                });

            modelBuilder.Entity("ProjektUrlopWeb.Models.Entities.Pracownik", b =>
                {
                    b.Property<int>("Id_num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_num"));

                    b.Property<DateTime>("DataZatr")
                        .HasColumnType("datetime2");

                    b.Property<int>("DniUrlopu")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArch")
                        .HasColumnType("bit");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_num");

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("ProjektUrlopWeb.Models.Entities.Urlop", b =>
                {
                    b.Property<int>("Id_num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_num"));

                    b.Property<DateTime>("DataRozp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZak")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IloscDni")
                        .HasColumnType("int");

                    b.Property<bool>("IsAppr")
                        .HasColumnType("bit");

                    b.Property<int>("PracownikId_num")
                        .HasColumnType("int");

                    b.Property<string>("Rodzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_num");

                    b.HasIndex("PracownikId_num");

                    b.ToTable("Urlopy");
                });

            modelBuilder.Entity("ProjektUrlopWeb.Models.Entities.Log", b =>
                {
                    b.HasOne("ProjektUrlopWeb.Models.Entities.Pracownik", "Pracownik")
                        .WithMany()
                        .HasForeignKey("PracownikId_num")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");
                });

            modelBuilder.Entity("ProjektUrlopWeb.Models.Entities.Urlop", b =>
                {
                    b.HasOne("ProjektUrlopWeb.Models.Entities.Pracownik", "Pracownik")
                        .WithMany()
                        .HasForeignKey("PracownikId_num")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");
                });
#pragma warning restore 612, 618
        }
    }
}
